# Generated by Django 6.0.3 on 2026-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='items_description',
            field=models.TextField(blank=True, help_text='Описание товаров, необходимых для заявки', verbose_name='Описание товаров'),
        ),
    ]
