# Generated by Django 6.0.3 on 2026-03-15 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_purchaseorder_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество в цеху')),
                ('location', models.CharField(blank=True, help_text='Например: Стеллаж А-3, Верстак 2', max_length=100, verbose_name='Место хранения')),
                ('min_quantity', models.PositiveIntegerField(default=5, help_text='При достижении этого уровня требуется пополнение со склада', verbose_name='Минимальный уровень запаса в цеху')),
                ('status', models.CharField(choices=[('normal', 'В норме'), ('low', 'Низкий запас')], default='normal', max_length=10, verbose_name='Статус')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_stocks', to='core.product', verbose_name='Товар')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_stocks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Запас цеха',
                'verbose_name_plural': 'Запасы цеха',
                'ordering': ['product__name'],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
