# Generated by Django 6.0.3 on 2026-03-21 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workshopstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе цеха')),
                ('location', models.CharField(blank=True, help_text='Например: Зона А-1, Секция Б-2', max_length=100, verbose_name='Место хранения')),
                ('min_quantity', models.PositiveIntegerField(default=50, help_text='При достижении этого уровня требуется заказ у поставщика', verbose_name='Минимальный уровень запаса')),
                ('max_quantity', models.PositiveIntegerField(default=1000, help_text='Максимально допустимое количество на складе', verbose_name='Максимальный уровень запаса')),
                ('status', models.CharField(choices=[('normal', 'В норме'), ('low', 'Низкий запас'), ('excess', 'Избыток')], default='normal', max_length=10, verbose_name='Статус')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_warehouses', to='core.product', verbose_name='Товар')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Склад цеха',
                'verbose_name_plural': 'Склады цеха',
                'ordering': ['product__name'],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
