# Generated by Django 6.0.4 on 2026-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_workshop_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sales_item',
            field=models.BooleanField(default=True, help_text='Если отмечено, товар предназначен для продажи клиентам', verbose_name='Товар для продажи'),
        ),
    ]
