# Generated by Django 6.0.4 on 2026-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_is_sales_item_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sales_item',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название материала'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе цеха'),
        ),
    ]
