# Generated by Django 6.0.3 on 2026-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_workshopstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopstock',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальное количество'),
        ),
    ]
