# Generated by Django 6.0.3 on 2026-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_add_min_quantity_to_workshopstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopstock',
            name='status',
            field=models.CharField(choices=[('normal', 'В норме'), ('low', 'Низкий запас')], default='normal', max_length=10, verbose_name='Статус'),
        ),
    ]
