# Generated by Django 6.0.3 on 2026-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_workshopstock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='items_description',
            field=models.TextField(blank=True, help_text='Описание товаров, необходимых для заявки', verbose_name='Описание товаров'),
        ),
    ]
