# Generated by Django 6.0.4 on 2026-04-12 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_purchaserequest_items_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopstock',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='workshopstock',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_stocks_managed', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
