# Generated by Django 6.0.4 on 2026-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_remove_workshopstock_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
