# Generated by Django 6.0.4 on 2026-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_requestitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('confirmed', 'Подтвержден'), ('partial', 'Частично исполнен'), ('completed', 'Исполнен'), ('cancelled', 'Отменен')], default='sent', max_length=20, verbose_name='Статус'),
        ),
    ]
