# Generated by Django 6.0.4 on 2026-04-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
    ]
